[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
# Cryptography and Math
allocative.workspace = true

# Tracing and profiling
tracing-chrome.workspace = true
tracing-subscriber.workspace = true
